create table if not exists goodde_yandex_turbo_feed (
	ID int(11) not null auto_increment,
	IBLOCK_ID int(11) not null,
	TIMESTAMP_X timestamp,
	MODIFIED_BY int(18),
	DATE_CREATE datetime,
	CREATED_BY int(18),
	ACTIVE varchar(1) not null default 'Y',
	ALL_FEED varchar(1) not null default 'N',
	LID varchar(2) not null,
	NAME varchar(255) not null,
	DETAIL_URL varchar(255) default null,
	IPROPERTY_TEMPLATES text default null,
	PRICE_CODE varchar(255) default null,
	SERVER_ADDRESS varchar(255) not null,
	DESCRIPTION text default null,
	SORT int(11) not null default '500',
	TEMPLATE varchar(100) not null default '.default',
	ITEM_STATUS varchar(20) default null,
	MENU text default null,
	FORM varchar(255) default null,
	FIGCAPTION_VIDEO varchar(255) default null,
	FEEDBACK text default null,
	CONTENT varchar(100) default 'DETAIL_TEXT',
	PUB_DATE varchar(20)  default null,
	`LIMIT` int(11) not null default '1000',
	ACTIVE_DATE varchar(1) not null default 'N',
	ELEMENTS_FILTER text null default null,
	OFFERS_FILTER text null default null,
	ELEMENTS_CONDITION text null default null,
	OFFERS_CONDITION text null default null,
	PROPERTY text default null,
	OFFERS_PROPERTY text default null,
	GALLERY varchar(255) default null,
	SECTIONS_FILTER text null default null,
	IS_SECTION varchar(1) not null default 'N',
	SECTIONS_ID longtext null default null,
	FIELDS longtext null default null,
	SECTION_URL varchar(255) default null,
	RELATED_LIMIT int(11) default '4',
	RELATED_SOURCE varchar(100) not null default 'QUEUE',
	SHARE_NETWORKS varchar(255) default null,
	DATE_ADD_FEED datetime,
	IS_NOT_UPLOAD_FEED varchar(1) not null default 'N',
	IN_AGENT varchar(1) not null default 'N',
	INDEX goodde_yandex_turbo_feed(IBLOCK_ID),
	primary key (ID)
)
ENGINE = InnoDB;

create table if not exists goodde_yandex_turbo_task (
	ID int(11) not null auto_increment,
	DATE_CREATE timestamp,
	NAME varchar(255) default null,
	FEED_ID int(11) not null,
	LID varchar(2) not null,
	TASK_ID varchar(255) not null,
	MODE varchar(10) default null,
	RSS_FEED_DELETE varchar(1) not null default 'N',
	primary key (ID),
	INDEX goodde_yandex_turbo_task(FEED_ID)
)
ENGINE = InnoDB;

create table if not exists goodde_yandex_turbo_profile (
	ID int(11) not null auto_increment,
	SORT int(11) null default '500',
	LID char(2) null default null,
	CHARSET varchar(255) null default null,
	TIMESTAMP_X timestamp,
	MODIFIED_BY int(18),
	DATE_CREATE datetime,
	CREATED_BY int(18),
	ACTIVE char(1) null default 'Y',
	NAME varchar(255) default null,
	`LIMIT` int(5) null default '100',
	FILE_PATH varchar(255) null default null,
	SHOP_NAME varchar(80) null default null,
	SHOP_COMPANY varchar(255) null default null,
	SHOP_URL varchar(255) null default null,
	CURRENCY longtext null default null,
	PRICE_CODE varchar(255) default null,
	DETAIL_URL varchar(255) default null,
	DELIVERY text null default null,
	DIMENSIONS text null default null,
	UTM_TAGS text null default null,
	USE_CATALOG char(1) null default 'Y',
	USE_SUBSECTIONS char(1) null default 'N',
	IBLOCK_TYPE_ID varchar(255) null default null,
	IBLOCK_ID int(11) not null,
	SECTION_ID text null default null,
	ELEMENTS_FILTER text null default null,
	OFFERS_FILTER text null default null,
	ELEMENTS_CONDITION text null default null,
	OFFERS_CONDITION text null default null,
	`TYPE` varchar(255) null default null,
	FIELDS longtext null default null,
	LAST_START datetime null default null,
	LAST_END datetime null default null,
	TOTAL_ITEMS int(11) null default '0',
	TOTAL_ELEMENTS int(11) null default '0',
	TOTAL_OFFERS int(11) null default '0',
	TOTAL_SECTIONS int(11) null default '0',
	TOTAL_RUN_TIME varchar(255) null default null,
	TOTAL_MEMORY varchar(255) null default null,
	IN_AGENT varchar(1) null default 'N',
	INDEX goodde_yandex_turbo_profile(IBLOCK_ID),
	primary key (ID)
)
ENGINE = InnoDB;